name: ${project.name}
main: vg.civcraft.mc.bettershards.BetterShardsPlugin
version: ${project.version}
author: Rourke750
depend: [Mercury]
commands:
 bsc:
  permission: bettershards.*
 bsd:
  permission: bettershards.*
 bsj:
  permission: bettershards.*
 bsr:
  permission: bettershards.*
 bse:
  permission: bettershards.*
 shard:
  permission: bettershards.player
permissions:
  bettershards.*:
   default: op
  bettershards.player:
   default: true
