name: ${project.name}
main: vg.civcraft.mc.bettershards.BetterShardsPlugin
version: ${releaseVersion}
author: Rourke750
depend: [Mercury, CivModCore]
softdepend: [NameLayer, CombatTagPlus, ProtocolLib]
commands:
 bsc:
  permission: bettershards.*
 bsd:
  permission: bettershards.*
 bsj:
  permission: bettershards.*
 bsr:
  permission: bettershards.*
 bse:
  permission: bettershards.*
 tp:
  permission: bettershards.*
 bts:
  permission: bettershards.*
 ts:
  permission: bettershards.*
permissions:
  bettershards.*:
   default: op
